### ISSUE TITLE
ライセンスについて

### ISSUE THREAD

**Issue by Rapilias** [oca-laful/illust#1]
README.mdにて
> イラスト用素材は改変・再配布自由です

と記載されていますが、
`illust/blue_archive/halo/` 以下に含まれるfbxファイルのうち、Kayoko / Mustuki 以外は他のユーザーが作成したように見受けられます。
しかし、コミットログの情報にあるユーザー名らしきものから実際のユーザーを特定する事が出来ず、ライセンス的に本当に利用可能であるかを判断できませんでした。
これらのリソースに関しての出典/規約ををリンク込みで明示して頂くことは可能でしょうか？

**Comment by oca-laful** [comment]
`illust/blue_archive/halo/このフォルダについて.txt` 内に
> https://twitter.com/texteater
> https://drive.google.com/drive/folders/1GJ8fJw9bV8wBBD37ZRFg8y1l2gc2X1VN

と既に記述していますが，より分かりやすくするためにREADME.mdにも追記しました．

GoogleDriveリンク先の`使い方_注意事項.jpg`には2022年7月16日現在「改変・再配布自由」と記述されていたため，`illust/blue_archive/halo/`でも使用しています．

（コミットログがわかりにくく申し訳ありません………）

**Comment by Rapilias** [comment]
> illust/blue_archive/halo/このフォルダについて.txt 

こちら見れてませんでした... 説明/追記頂きありがとうございます。
